### ISSUE TITLE
makefile release target does not exists

### ISSUE THREAD

**Issue by genadipost** [chef/chef-web-docs#159]
From README.MD, [**Building Docs**](https://github.com/chef/chef-web-docs#building-docs):

```
## Building Docs

There's a `Makefile` in the root of the repo, that should have the majority of the tasks you'll ever need.

Run:

    make release

This will build *all* the documentation into HTML, and place it inside `./build/chef/`.
Open `./build/chef/index.html` to view the rendered files locally.

```

But the target does not exists in the [Makefile](https://github.com/chef/chef-web-docs/blob/master/Makefile) (master branch) and will cause an error when running it.

```
[genadi@localhost chef-web-docs]# make release
make: *** No rule to make target `release'.  Stop.
```

**Comment by davidwrede** [comment]
@genadipost, thanks for providing the feedback. We have since updated both the README.md and Makefile, so now you should be able to simply call the default target via `make` to build the current doc set. All of the previous doc sets now live on docs-archive.chef.io and the source files for these scoped doc sets will soon be removed from the chef-web-docs repo. 

Any missing, but current content (such as Analytics) will be re-integrated in the main left-nav of the site.
