### ISSUE TITLE
Launchd docs are wrong

### ISSUE THREAD

**Issue by natewalck** [chef/chef-web-docs#18]
@jamescott , It looks like some wires are crossed.

**resource_osx_profile** is completely different from **resource_launchd**.

It looks like some terminology and actions from **osx_profile**: https://docs.chef.io/release/12-7/resource_osx_profile.html

Ended up in the documentation for **resource_launchd**:

https://docs.chef.io/release/12-8/resource_launchd.html

A **launchd** is _not_ a configuration profile. It is a completely different resource. The way it is referred to in this PR is correct (  "...resource to manage launchd daemons / agents") but in the documentation you linked, it says "A launchd resource to manage configuration profiles (.mobileconfig files) on the Mac OS X platform", which is **not** correct.

For instance:

resource_osx_profile is a .mobileconfig file

resource_launchd is a **.plist** file

A resource_launchd is a service like cron or upstart. It is not a configuration profile at all. It is a service.

Thanks for getting the docs updated! Let us know if any further clarification is needed.

**Comment by jamescott** [comment]
... and rebuilt: https://docs.chef.io/resource_launchd.html

Should be good to go now.

**Comment by natewalck** [comment]
Looking much better.

Under actions, it still says 'configuration profile'. It should match what was in the original documentation commit. For all the correct action descriptions, please see:

https://github.com/chef/chef-web-docs-2016/pull/793/files#diff-9c0631ec3662888ec31075b436323f93R4

Thanks!

**Comment by natewalck** [comment]
Also, I'm curious...was there something wrong with this PR? https://github.com/chef/chef-web-docs-2016/pull/793

We want to help update docs as we make providers and update existing providers, so if we are doing it wrong, let us know and we would be more than happy to submit PRs in the desired fashion.

**Comment by jamescott** [comment]
There was only one thing wrong with that PR: it was against the "current version" doc set (chef_master) which at the time was 12.6(?). The versioned doc repos are in the release_chef_12-x and this resource slipped from one release to the next as well. It was otherwise a terrific PR however.

And then the other thing that happened in-between your PR and the shipping date is that we changed the chef-web-docs repo to remove the massive commit history so that our build processes could be faster. The PR moved with the change to the -2016 repo.

I do apologize for the extra back and forth on the editing here. Just pushed a change to the actions descriptions.

**Comment by natewalck** [comment]
@jamescott No worries! Mike and I just wanted to make sure we were doing it correctly. So in the future, where should our documentation PRs go? This repo?

Thanks again!

**Comment by jamescott** [comment]
Yeah. The chef-web-docs repo is correct. The one with the -2016 is the old repo with the old history kept for historical purposes.

**Comment by jamescott** [comment]
OK to close this out as fixed?

**Comment by natewalck** [comment]
Looks good to me! 

When will the live docs reflect the changes?

**Comment by jamescott** [comment]
The most recent change is in our pipeline right now.
