### ISSUE TITLE
Address bugs currently living in chef-web-docs-2016 repo

### ISSUE THREAD

**Issue by vinyar** [chef/chef-web-docs#238]
It seems that since the time docs page was split into the new repo and 2016, there is still a number of bugs in the 2016 repo, which are relevant but seem to be ignored. 

These bugs should not be closed as it seems, instead, it would be great if they were migrated into this repo and prioritized along side with current bugs.

**Comment by davidwrede** [comment]
Hey @vinyar, we will start migrating any current and relevant issues in the chef-web-docs-2016 repo over to the chef-web-docs repo as part of an on-going process to get through our GH PR and issue backlog. Because of the volume, this activity will take some time.

Can you refer me to a bug or issue that was closed without some resolution specified? With the exception of https://github.com/chef/chef-web-docs-2016/pull/772 (which refers to outdated products), any closed PRs or issues should have some resolution attached to them so that they don't appear to be closed without explanation. If that's not the case, then I'm happy to go in and take a look at them.

Thanks,
Dave

**Comment by vinyar** [comment]
Hi @davidwrede I don't have a specific bug today. I'll flag 'em next time I hit an issue.
Feel free to close.
