### ISSUE TITLE
chef_group issue with adding user

### ISSUE THREAD

**Issue by pariminaresh** [chef/chef-web-docs#270]
I see couple of unexpected behaviors with chef_group resource.Please clarify me if those as expected or issues to be fixed.

1.Here is a case, where if the group doesn't exists and it creates the group and skips the adding user to the group.

chef_group "group1" do
        name "group1"
        chef_server hash
        users "user1"
end

With the above resource definition, first time execution just creates the group 'group1' and doesn't add the user to group.Need to execute the same once again to add the user.

2. There is no check if the user exists on server side.Still the resource tries to update the group on the server even if the user doesn't exists.To avoid this need to explicitly add a check point to see the user exists(knife).

3. Strict validation on name.Validation fails on resource name if there is any spaces.Not sure this is what intended here.
'Property name must be one of: /^[.\-[:alnum:]_]+$/!  You passed "Create group group_read"

4. chef_server  attribute is not string as mentioned in the documentations, infant it expects hash.

Hope it helps to improvise the chef_group resource.

Thanks

**Comment by brewn** [comment]
Sorry for not getting to this sooner. Since this issue doesn't appear to be documentation related, I'd recommend either reaching out to our community via [Slack](http://community-slack.chef.io/) or [Discourse](http://discourse.chef.io). Alternatively, you could open an issue under the [Chef repo](https://github.com/chef/chef).
