### ISSUE TITLE
The Cookstyle docs should contain instructions on disabling via commenting  

### ISSUE THREAD

**Issue by jordan3825** [chef/chef-web-docs#2963]
### User Story
As a <role: Developer, SysAdmin, etc.>, I want to use the docs to understand how to disable cookstyle rules on a case by case basis in code. 

## Description
Document the cookstyle disable comments are not documented. Cookstyle specific comments were added in 5.12 but have not been added to the documentation.  

https://github.com/chef/cookstyle/blob/master/RELEASE_NOTES.md#cookstyle-comments-in-code

## Chef Version
Cookstyle 5.12+

## Platform Version
N/A

### Definition of Done
The cookstyle comments are documented. 

### Demo Script / Repro Steps
View https://docs.chef.io/workstation/cookstyle/ and note that it does not contain the information from the release notes: https://github.com/chef/cookstyle/blob/master/RELEASE_NOTES.md#cookstyle-comments-in-code

**Comment by carlosaya** [comment]
3.5 years later and still not done?  at least I was able to find the link in this issue I guess 🤷‍♂️

**Comment by Stromweld** [comment]
Cookstyle is basically a set of rules for rubocop. All rubocop documentation on disabling/enabling rules apply then.

**Comment by carlosaya** [comment]
While what you say is true, I have to wonder why someone felt the need to include this information in the cookstyle release notes at all then?  It's also no real additional burden to include the same information on the official Chef cookstyle page, so I'd argue there's no good reason NOT to include it, especially since the page in question already goes into detail about disabling via .rubocop.yml.

**Comment by IanMadd** [comment]
Deployed in #4240
