### ISSUE TITLE
Automate the Infra Server release notes

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3025]
### User Story
As a SysAdmin, I will use this work when I want to see the latest Chef Infra Server release notes.

As a Developer, I will use this work when I want to not worry about manual promotion processes.

## Description
Right now we handle release notes for Infra Server in the wiki and we auto announce to discourse, but we don't manually promote these to the the website. We should create a structure similar to that in Workstation and automate the release not process so we make sure we always have the latest docs up on the site.

**Comment by IanMadd** [comment]
The easy part is making a Server release notes page that works the same way as the Automate and InSpec. The problem is that the S3 bucket that contains the release notes only has release notes going back to version 14.0.58. If we make the switch, we'll lose everything before then. So the first step is to add those earlier release notes to S3 and then we can make the switch.

**Comment by IanMadd** [comment]
Closed with #3301
