### ISSUE TITLE
"[INTAKE] Document Hosted Chef"

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#3581]
# Large documentation  project plan

Hosted Chef (manage.chef.io) is one of our offerings and one that has a fairly devoted customer base. While we hope to migrate existing users to Chef Automate, either now or in the future, we should provide at least _basic_ documentation for Hosted Chef users.

Advantages:

- Providing documentation for our products is the best practice.
- Providing documentation will reduce customer service calls.
- Providing documentation gives us the opportunity to understand the reasons that users stay with Hosted Chef 
- Providing documentation gives us the opportunity to communicate directly with Hosted Chef users about the benefits of Chef Automate
- Providing documentation for users is the right thing to do.

**Comment by sean-horn** [comment]
We recently had an internal conversation over several days that took a combined total of 5 hours of Chefs' time concerning a new customer's Hosted Chef onboarding. This is interesting as there has never been any sort of manual or hands-on onboarding for Hosted Chef customers. An onboarding for Hosted Chef doesn't exist, as the historical docs to get started are simple and easy to follow. As the patronage of Hosted Chef continues to grow, so will this area of interest. The trend of spending time on these could be minimized with simple docs.

During our discussion, we discovered the docs for this purpose are no longer there at docs.chef.io; no discussion of Hosted Chef at all. This is the key. We never previously had any questions or concerns about how to get started with Hosted Chef, as the process was documented and available for reference by account teams and customers.

We want customers to onboard themselves to Hosted Chef. The way to do that is to restore the minimum docs that discuss the process, so that customers can get themselves going rapidly. It's not difficult but is time consuming and a low priority concern where resources could be better spent.

**Comment by kagarmoe** [comment]
Include #3517 in the current work.
