### ISSUE TITLE
chef compliance has conflicting instructions

### ISSUE THREAD

**Issue by spuder** [chef/chef-web-docs#407]
On this page of the chef compliance install instructions, it says to use an '=' when configuring /etc/chef-compliance/chef-compliance.rb

https://docs.chef.io/install_compliance.html#configure-ssl

![screenshot 2017-01-23 11 38 08](https://cloud.githubusercontent.com/assets/242382/22217481/6fee20f2-e160-11e6-9a19-cf343b003946.png)

Yet on this page, it says to not use equal signs and the examples show no equals 

https://docs.chef.io/config_rb_compliance.html#settings

![screenshot 2017-01-23 11 39 49](https://cloud.githubusercontent.com/assets/242382/22217570/bdb4c96c-e160-11e6-89bc-3b7729009b4f.png)

So which am I supposed to use?

**Comment by srenatus** [comment]
@spuder this is using mixlib-config, [so *both* are possible](https://github.com/chef/mixlib-config/blob/274562f1b845e756d17731b9f2019abca2edebbf/lib/mixlib/config.rb#L490-L506) for ssl certificate and certificate_key. The difference to `fqdn` and `verify_tls` is that

```
ssl.certificate '/etc/chef-compliance/ssl/my.crt'
```
would be "translated" (not really, but you can think of it like that) to
```
ssl['certificate'] = '/etc/chef-compliance/ssl/my.crt'
```

whereas there's no way to that for `fqdn` or `verify_tls` -- which is why *that* paragraph is explicit about
> Do *not* use `=` to set the option.

Does that clear things up?
