### ISSUE TITLE
ERROR: ArgumentError: unknown proxy scheme `https'

### ISSUE THREAD

**Issue by sasideveloper** [chef/chef-web-docs#480]
Hi,

When we set https_proxy value in knife.rb, we are getting below error. 

Command : knife ssl check https://manage.chef.io
Output : ERROR: ArgumentError: unknown proxy scheme `https'

Where as when we use only http_proxy, command is working fine. Please let us know what is wrong.

**Comment by jmaybe** [comment]
Hi,
I ran into the same problem a few minutes ago. Granted, I don't know what system or proxy you are using, but the following worked for me. 
(I have a caching server/reverse proxy running and am using a newly configured laptop with Ubuntu 16.10. I had only set the proxy values in /apt/apt.conf.d/10proxy so far to pull from update cache)

In order to fix the above problem I did the following:

>$: sudo vi /etc/profile
\# add follows to the end (set proxy settings to the environment variables)

>MY_PROXY_URL="http://address.of.proxy.server:port/"
HTTP_PROXY=$MY_PROXY_URL
HTTPS_PROXY=$MY_PROXY_URL
FTP_PROXY=$MY_PROXY_URL
http_proxy=$MY_PROXY_URL
https_proxy=$MY_PROXY_URL
ftp_proxy=$MY_PROXY_URL

>export HTTP_PROXY HTTPS_PROXY FTP_PROXY http_proxy https_proxy ftp_proxy

>$: sudo source /etc/profile

Then I changed back into /.chef and ran 

>$: knife ssl check
Connecting to host api.chef.io:443
Successfully verified certificates from 'api.chef.io:443'

Hopefully that helps somebody.

**Comment by brewn** [comment]
Sorry to get to this a bit late, but you'd have more luck getting timely answers to these sort of questions on our Discourse: https://discourse.chef.io/

There's a potential solution here, where the user was able to get this working by updating the environmental variable to use http:

https://discourse.chef.io/t/unknown-proxy-scheme-https/10604

I'd take a look at the output of `env | grep proxy` to confirm.
