### ISSUE TITLE
Elaborate on default action on custom resource example

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef-web-docs#835]
On this page describing Custom Resources: https://docs.chef.io/custom_resources.html

It defines a custom resource referred to as `exampleco_site` like this:

```
property :homepage, String, default: '<h1>Hello world!</h1>'

action :create do
  package 'httpd'

  service 'httpd' do
    action [:enable, :start]
  end

  file '/var/www/html/index.html' do
    content homepage
  end
end

action :delete do
  package 'httpd' do
    action :delete
  end
end
```

After the declaration the page says that `create` is the default action. Why is this?

- Is it because it is listed first?
- Or is it a bug and the example should have a line at the top saying: `default_action :create`

I don't know which one is the right answer, otherwise I will be happy to contribute :)

**Comment by brewn** [comment]
Hi Martin, 

It's the default because it's listed first. This is mentioned in the [syntax section](https://docs.chef.io/custom_resources.html#syntax) but I agree that it's not made very transparent in the example that follows. 

It's also possible to manually set the default action with `default_action`: https://docs.chef.io/dsl_custom_resource.html#default-action

I'm working on clearing this up here: https://github.com/chef/chef-web-docs/pull/836

**Comment by martinmosegaard** [comment]
Thanks a lot - I guess the highlighting in the Example section caught my eye and I must have skipped the Syntax section.

**Comment by brewn** [comment]
No problem! Thanks for pointing this out.
